<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <PackageId>SdkPackLicenseSample</PackageId>
    <Version>1.0.0</Version>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <NuGetize>false</NuGetize>
    <ImportNuGetBuildTasksPackTargetsFromSdk>true</ImportNuGetBuildTasksPackTargetsFromSdk>
    <PackageLicenseFile>OSMFEULA.txt</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="OSMFEULA.txt" Pack="true" PackagePath="OSMFEULA.txt" />
    <None Include="NOTICE.txt" Pack="true" PackagePath="NOTICE.txt" />
  </ItemGroup>
</Project>
